### ISSUE TITLE
Preserve card location

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/pico-engine-ui#12]
We need to save the position of the card in the settings variable. Currently, refreshing the tab sets everything back to the start.

**Comment by windley** [comment]
In CloudOS, there was a set of specific events and queries for managing config information in the PDS. By putting it in the PDS, you can access it from any ruleset.

**Comment by cgrimm013** [comment]
We already have a ruleset for the ui itself. Since the position relates only to viewing the card in context of the UI, I don't see any reason for other rulesets to want or need access to its position. If two different people are viewing the same pico, but in context of their own UI view, the position will be different depending on what they used as their root pico for the UI, which is motivation to avoid localizing it on a per pico basis. Instead, the UI is built and configured from an "entry" pico. Thoughts?

**Comment by windley** [comment]
That particular piece of configuration might not need to be shared widely. The question is do you want to store this kind of data ad hoc or have a consistent way of storing config data for the UI? And if so, how are you going to do it?

**Comment by cgrimm013** [comment]
The config data is going to be stored in the entry pico's ui ruleset entity variable(s). Whatever pico someone first "enters" has the ui ruleset installed and is used as the config location for all ui persistent data. If I used a different pico as an entry point, the config data would come from that pico instead.
