### ISSUE TITLE
App header/sidebar

### ISSUE THREAD

**Issue by cgrimm013** [Picolab/pico-engine-ui#6]
![uploads/66908c7f-7cf7-4d99-b525-fbc93b4ec003/IMG_2378.JPG](https://s3-us-west-2.amazonaws.com/prod.huboard.com/uploads%2F66908c7f-7cf7-4d99-b525-fbc93b4ec003%2FIMG_2378.JPG)

The left drawer/sidebar should not shade out the app, but can also be collapsible via the button on the far left of the app header. This sidebar will be used for all settings general to the entire application, such as theme settings and what relationship lines should be displayed.

**Comment by KandareJ** [comment]
Adjusted the layout of the app bar to look like the diagram, added a sidebar, and made the logout button functional
